#!/usr/bin/env python2

# -*- coding: utf-8 -*-

#
# Author: Mihai Galos
# Date: November 7 , 2018
# Purpose: indicator for the Netatmo Weather Station
# Tested on: Ubuntu 16.04 LTS
#
#
# Licensed under The MIT License (MIT).
# See included LICENSE file or the notice below.
#
# Copyright (c) 2018 Mihai Galos
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import appindicator
import gtk, glib
import datetime

from Drivers.Bluetooth.bluetooth import BluetoothModule

class AboutDialog:

    def __init__(self):

        self.dialog = gtk.Dialog("About",
                                 None,
                                 gtk.DIALOG_DESTROY_WITH_PARENT)

        self.dialog.set_default_size(150, 100)

        author = gtk.Label("(c) Mihai Galos 2018.")
        self.dialog.vbox.add(author)
        author.show()

        version = gtk.Label("v0.1-1")
        self.dialog.vbox.add(version)
        version.show()

        homepage = gtk.Label()
        homepage.set_markup("<a href=\"https://github.com/mihaigalos/bluetooth-module-indicator\">https://github.com/mihaigalos/bluetooth-module-indicator</a>")
        self.dialog.vbox.add(homepage)
        homepage.show()

        self.ok_button = gtk.Button("Ok")
        self.ok_button.connect("pressed", self.on_ok_button_pressed)
        self.dialog.vbox.pack_start(self.ok_button, False, False, 1)
        self.ok_button.show()

        self.dialog.run()

    def on_ok_button_pressed(self, *args):
        self.dialog.destroy()

class Menu:

    def __init__(self):
        self.create_menu()
        self.menu.show()

    def create_about_item(self):
        img = gtk.Image()
        img.set_from_stock(gtk.STOCK_HELP, 1)

        about_item = gtk.ImageMenuItem("About")
        about_item.set_image(img)
        about_item.set_always_show_image(True)
        about_item.connect("activate", self.on_about_clicked)
        about_item.show()
        self.menu.append(about_item)

    def create_menu(self):
        self.menu = gtk.Menu()
        self.create_timediff_item()
        self.create_separator()
        self.create_about_item()
        self.create_quit_item()

    def create_quit_item(self):
        img = gtk.Image()
        img.set_from_stock(gtk.STOCK_QUIT, 1)

        quit_item = gtk.ImageMenuItem("Quit")
        quit_item.set_image(img)
        quit_item.set_always_show_image(True)
        quit_item.connect("activate", self.quit)
        quit_item.show()
        self.menu.append(quit_item)

    def create_separator(self):
        separator = gtk.SeparatorMenuItem()
        separator.show()
        self.menu.append(separator)

    def create_timediff_item(self):
        img = gtk.Image()
        img.set_from_stock(gtk.STOCK_DIALOG_INFO, 1)
        self.timediff_item = gtk.ImageMenuItem("--")
        self.timediff_item.set_image(img)
        self.timediff_item.set_always_show_image(True)
        self.timediff_item.show()
        self.menu.append(self.timediff_item)

    def on_about_clicked(self, *args):
        about = AboutDialog()

    def set_diff_time_item_label(self, new_label):
        self.timediff_item.set_label(new_label)

    def quit(self, widget):
        gtk.main_quit()

class BluetoothModuleIndicator:
    def __init__(self, bluetooth_address, timeout_interval_msec=1*1000):

        self.last_timestamp = datetime.datetime.now()
        self.timeout_interval_msec = timeout_interval_msec
        self.setup_bluetooth(bluetooth_address)
        self.setup_window()
        self.setup_menu()
        self.setup_update()

    def compute_timestamp_diff(self):
        timestamp = datetime.datetime.now()
        time_diff = timestamp - self.last_timestamp
        self.last_timestamp = datetime.datetime.now()
        diff_seconds  = time_diff.total_seconds()

        if(diff_seconds > 5*60):
            diff_seconds = "--"
        else:
            diff_seconds = str(int(diff_seconds))

        return diff_seconds

    def get_timediff_label(self):
        return 'Retrieved ' + self.compute_timestamp_diff() + "s ago."

    def on_update(self):
        self.menu.set_diff_time_item_label(self.get_timediff_label())
        glib.timeout_add(self.timeout_interval_msec, self.on_update)

    def setup_bluetooth(self, bluetooth_address):
        try:
            self.bluetooth_module = BluetoothModule(bluetooth_address)
            self.label = self.bluetooth_module.read(once=True)
        except:
            self.label = str("No reply from  " + bluetooth_address)
            pass

    def setup_menu(self):
        self.menu = Menu()
        self.indicator.set_menu(self.menu.menu)

    def setup_update(self):
        glib.timeout_add(self.timeout_interval_msec, self.on_update)

    def setup_window(self):
        self.indicator = appindicator.Indicator("sample-ind", "bluetooth-active",
                                                appindicator.CATEGORY_APPLICATION_STATUS)
        self.indicator.set_status(appindicator.STATUS_ACTIVE)
        self.indicator.set_label(self.label)


def main():
    gtk.main()
    return 0

if __name__ == "__main__":
    indicator = BluetoothModuleIndicator("3C:A5:39:90:BB:B1")
main()